version: '3'
services:
  pdf_api:
    container_name: pdf_api
    restart: always
    build: https://github.com/Rob192/pdf_api.git#:pdf_api
    ports:
      - "8011:8000"
    command: gunicorn -w 2 --timeout 90 -b 0.0.0.0:8000 wsgi:app
    
  pdf_app:
    container_name: pdf_app
    restart: always
    build: ./pdf_app
    ports:
      - "8010:8050"
    command: gunicorn -w 1 --timeout 90 -b 0.0.0.0:8050 app:server
    depends_on:
      - pdf_api
  
  nginx_pdf:
    container_name: nginx_pdf
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - pdf_api
      - pdf_app
